_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 77
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 77
                - 98
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 8
epochs:
    value: 10
filepath:
    value: 10-1e-05-sonnet.pt
held_out_sonnet_path:
    value: data/sonnets_held_out_dev.txt
lr:
    value: 1e-05
model_size:
    value: gpt2-large
seed:
    value: 11711
sonnet_out:
    value: predictions/generated_sonnets_dev.txt
sonnet_path:
    value: data/sonnets.txt
temperature:
    value: 1.2
top_p:
    value: 0.9
use_gpu:
    value: false
use_graph:
    value: false
use_kan:
    value: false
use_lora:
    value: true
wandb_config_file:
    value: ""
weight_decay:
    value: 0
